### ISSUE TITLE
Slack registration link not working

### ISSUE THREAD

**Issue by rafalmag** [wroclawjug/wroclawjug.github.io#28]
Hi,
I am a little bit newbie about using Slack and regarding:

> Slack - tutaj też możemy podyskutować. **Rejestracja**, adress Slacka: jvm-poland.slack.com Kanał: #meetup-wroclaw-jug

The registration link is not working. I assume that without prior invite I am not able to join Slack channel myself?

Please advise.

**Comment by mstachniuk** [comment]
Hi, please check this one: http://jvm-poland-slackin.herokuapp.com/

As I know the signup.team is shutdown and the above link is the new one. Please confirm and update a link in the project!

**Comment by rafalmag** [comment]
The new link is working. Please review PR #29 .

**Comment by rafalmag** [comment]
PR merged - issue can be closed :)
